# https://rainboard.laas.fr/project/pinocchio/.gitlab-ci.yml

.robotpkg-pinocchio: &robotpkg-pinocchio
  retry:
    max: 2
    when: runner_system_failure
  except:
    - gh-pages
  script:
    - cd /root/robotpkg/math
    - git pull
    - cd pinocchio
    - make checkout MASTER_REPOSITORY="git ${CI_PROJECT_DIR}/.git"
    - make install
    - build=$(make show-var VARNAME=CONFIGURE_DIRS); cd $(make show-var VARNAME=WRKSRC); cd $build
    - make test

robotpkg-pinocchio-18.04:
  <<: *robotpkg-pinocchio
  image: gepetto/buildfarm:pinocchio-18.04
  allow_failure: true
  
.robotpkg-py-pinocchio: &robotpkg-py-pinocchio
  retry:
    max: 2
    when: runner_system_failure
  except:
    - gh-pages
  script:
    - cd /root/robotpkg/math
    - git pull
    - cd pinocchio
    - make checkout MASTER_REPOSITORY="git ${CI_PROJECT_DIR}/.git"
    - cd ..
    - cd py-pinocchio
    - make checkout MASTER_REPOSITORY="git ${CI_PROJECT_DIR}/.git"
    - make install
    - build=$(make show-var VARNAME=CONFIGURE_DIRS); cd $(make show-var VARNAME=WRKSRC); cd $build
    - make test
    
robotpkg-py-pinocchio-18.04:
  <<: *robotpkg-py-pinocchio
  image: gepetto/buildfarm:py-pinocchio-18.04
  allow_failure: true

doc-coverage:
  <<: *robotpkg-py-pinocchio
  image: gepetto/buildfarm:py-pinocchio-20.04
  before_script:
    - echo -e 'CXXFLAGS+= --coverage\nLDFLAGS+= --coverage\nPKG_DEFAULT_OPTIONS= debug' >> /opt/openrobots/etc/robotpkg.conf
  after_script:
    - cd /root/robotpkg/math/py-pinocchio
    - build=$(make show-var VARNAME=CONFIGURE_DIRS); cd $(make show-var VARNAME=WRKSRC); cd $build
    - make doc
    - mv doc/doxygen-html ${CI_PROJECT_DIR}
    - mkdir -p ${CI_PROJECT_DIR}/coverage/
    - gcovr -e CMakeFiles -e _deps -r .
    - gcovr -e CMakeFiles -e _deps -r . --html --html-details -o ${CI_PROJECT_DIR}/coverage/index.html
  artifacts:
    expire_in: 1 day
    paths:
      - doxygen-html/
      - coverage/