name: pinocchio
channels:
  - conda-forge
  - nodefaults
dependencies:
  - eigen=3.4.0
  - hpp-fcl
  - numpy
  - boost
  - eigenpy
  - urdfdom
  - python
  - mamba
  - cmake
  - ccache
  - llvm-openmp
  - cxx-compiler
  - pkg-config
